def report_writer_prompt(sourcing_report:str, network_report: str, risk_report: str, customer_report: str, market_report: str, pricing_report: str, negotiation_report: str) -> str:
    return (
        "Create an HTML report from the following markdown content:"
        f"'Customer Profile & Historical Analysis: {customer_report}\n"
        f"Market & Industry Analysis: {market_report}\n"
        f"Energy Cost & Network Capacity: {sourcing_report}\n{network_report}\n"
        f"Risk & Financial Assessment: {risk_report}"
        f"Pricing Strategy & Commercial Opportunities: {pricing_report}\n"
        f"Negotiation Strategy & Next Steps: {negotiation_report}'\n"
        "All content provided should be included in the final report unless there is a repetition."
        "The content should have headers and sub-headers where appropriate."
        
        "If url sources are provided, ensure they are included as hyperlinks."
        
        "Ensure any images provided by the workers are included using <img> tags and that "
        "the output adheres to the following HTML styling:"
        "\n"
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Negotiation Insights</title>\n"
        "    <style>\n"
        "        body {\n"
        "            font-family: \"Helvetica Neue\", Arial, sans-serif;\n"
        "            line-height: 1.6;\n"
        "            margin: 0;\n"
        "            padding: 0;\n"
        "            background-color: #ffffff;\n"
        "            color: #333;\n"
        "        }\n"
        "        header {\n"
        "            background-color: #86BC25;\n"
        "            padding: 10px;\n"
        "            text-align: center;\n"
        "            position: relative;\n"
        "        }\n"
        "        header img {\n"
        "            height: 50px;\n"
        "            vertical-align: middle;\n"
        "        }\n"
        "        header h1 {\n"
        "            color: #ffffff;\n"
        "            display: inline-block;\n"
        "            margin: 0;\n"
        "            font-size: 24px;\n"
        "            vertical-align: middle;\n"
        "        }\n"
        "        main {\n"
        "            padding: 20px;\n"
        "            max-width: 800px;\n"
        "            margin: auto;\n"
        "        }\n"
        "        h2, h3, h4 {\n"
        "            color: #0A2342;\n"
        "        }\n"
        "        h2 {\n"
        "            margin-top: 40px;\n"
        "            border-bottom: 2px solid #0A2342;\n"
        "            padding-bottom: 5px;\n"
        "        }\n"
        "        h3 {\n"
        "            margin-top: 30px;\n"
        "        }\n"
        "        h4 {\n"
        "            margin-top: 20px;\n"
        "        }\n"
        "        p {\n"
        "            margin-bottom: 10px;\n"
        "        }\n"
        "        img {\n"
        "            display: block;\n"
        "            margin: 20px auto;\n"
        "            max-width: 100%;\n"
        "            height: auto;\n"
        "        }\n"
        "        table {\n"
        "            width: 100%;\n"
        "            border-collapse: collapse;\n"
        "            margin: 20px 0;\n"
        "        }\n"
        "        th, td {\n"
        "            padding: 10px;\n"
        "            text-align: left;\n"
        "            border-bottom: 1px solid #ddd;\n"
        "        }\n"
        "        th {\n"
        "            background-color: #0A2342;\n"
        "            color: white;\n"
        "        }\n"
        "        ul {\n"
        "            list-style-type: disc;\n"
        "            margin: 10px 0 10px 20px;\n"
        "        }\n"
        "        li {\n"
        "            margin-bottom: 5px;\n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "\n"
        "<header>\n"
        "    <img src=\"deloitte_logo.png\" alt=\"Company Logo\">\n"
        "    <h1>Deal Negotiation Insights</h1>\n"
        "</header>\n"
        "\n"
        "<main>\n"
        "    <!--Add markdown content-->\n"
        "</main>\n"
        "\n"
        "</body>\n"
        "</html>\n"
        "\n"
        "Your report must follow this format exactly,"
        "ensuring content is well-organized, headers are used appropriately,"
        "and visual elements like images and tables are included where relevant."
        "Respond only with the complete HTML output when finished no additional explanations."
        )
